server:
  port: 8788
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
springfox:
  documentation:
    swagger-ui:
      enabled: true